// frontend/atomic/angular-signals/src/app/components/order-details.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { OrderFacade, OrderQuery } from '../state';

@Component({
  selector: 'app-order-details',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div *ngIf="order() as order; else empty" class="order-details">
      <div class="order-header">
        <h2>Заказ #{{order.id}}</h2>
        <button (click)="facade.toggleFavorite(order.id)" class="favorite-btn" [class.active]="facade.isFavorite(order.id)">
          {{ facade.isFavorite(order.id) ? '★' : '☆' }} Избранное
        </button>
      </div>

      <div class="order-info">
        <p><strong>Клиент:</strong> {{order.customer}}</p>
        <p><strong>Адрес:</strong> {{order.address}}</p>
        <p><strong>Трек-номер:</strong> {{order.trackingNumber}}</p>
        <p><strong>Статус:</strong> <span class="status status-{{order.status}}">{{order.status}}</span></p>
      </div>

      <div class="order-progress">
        <h3>Прогресс доставки</h3>
        <div class="progress-steps">
          <div *ngFor="let step of order.steps" class="step" [class.completed]="step.completed">
            <div class="step-marker"></div>
            <div class="step-info">
              <div class="step-status">{{ step.status }}</div>
              <div class="step-time" *ngIf="step.time">{{ step.time | date:'dd.MM.yyyy HH:mm' }}</div>
            </div>
          </div>
        </div>
      </div>

      <div class="order-items">
        <h3>Товары в заказе</h3>
        <table>
          <thead>
            <tr><th>Наименование</th><th>Количество</th><th>Цена</th><th>Сумма</th></tr>
          </thead>
          <tbody>
            <tr *ngFor="let item of order.items">
              <td>{{item.name}}</td>
              <td>{{item.quantity}}</td>
              <td>{{item.price | number}} ₽</td>
              <td>{{item.price * item.quantity | number}} ₽</td>
            </tr>
          </tbody>
          <tfoot>
            <tr><td colspan="3"><strong>Итого:</strong></td><td><strong>{{order.totalPrice | number}} ₽</strong></td></tr>
          </tfoot>
        </table>
      </div>

      <div class="order-actions">
        <button (click)="refresh(order.id)" class="refresh-btn">🔄 Обновить</button>
        <select *ngIf="order.status !== 'delivered'" (change)="changeStatus(order.id, $any($event.target).value)" [value]="''">
          <option value="" disabled>Изменить статус</option>
          <option *ngFor="let s of statuses" [value]="s" [hidden]="s === order.status">{{s}}</option>
        </select>
      </div>
    </div>
    <ng-template #empty>
      <div class="order-details-empty">
        <p>Введите номер заказа для отслеживания</p>
        <p class="hint">Попробуйте: 12345, 67890, 99999</p>
      </div>
    </ng-template>
  `,
  styles: [],
})
export class OrderDetailsComponent {
  private query = inject(OrderQuery);
  order = this.query.currentOrder;

  statuses = ['created', 'processing', 'shipped', 'delivered'];

  constructor(public facade: OrderFacade) {}

  refresh(id: string) {
    this.facade.fetchOrder(id);
  }

  changeStatus(id: string, status: string) {
    if (status) {
      this.facade.updateOrderStatus(id, status);
    }
  }
}

// frontend/atomic/mobx/src/components/OrderDetails.jsx
import React from 'react';
import { observer } from 'mobx-react-lite';
import { useOrderStore } from '../hooks/useOrderStore';
import { useOrderActions } from '../hooks/useOrderActions';

export const OrderDetails = observer(() => {
    const store = useOrderStore();
    const currentOrder = store.currentOrder;
    const { toggleFavorite, fetchOrder, updateOrderStatus, isFavorite } = useOrderActions();

    if (!currentOrder) {
        return (
            <div className="order-details-empty">
                <p>Введите номер заказа для отслеживания</p>
                <p className="hint">Попробуйте: 12345, 67890, 99999</p>
            </div>
        );
    }

    const isOrderFavorite = isFavorite(currentOrder.id);

    const handleStatusChange = (newStatus) => {
        updateOrderStatus(currentOrder.id, newStatus);
    };

    return (
        <div className="order-details">
            <div className="order-header">
                <h2>Заказ #{currentOrder.id}</h2>
                <button
                    onClick={() => toggleFavorite(currentOrder.id)}
                    className={`favorite-btn ${isOrderFavorite ? 'active' : ''}`}
                >
                    {isOrderFavorite ? '★' : '☆'} Избранное
                </button>
            </div>

            <div className="order-info">
                <p><strong>Клиент:</strong> {currentOrder.customer}</p>
                <p><strong>Адрес:</strong> {currentOrder.address}</p>
                <p><strong>Трек-номер:</strong> {currentOrder.trackingNumber}</p>
                <p><strong>Статус:</strong>
                    <span className={`status status-${currentOrder.status}`}>
            {currentOrder.status}
          </span>
                </p>
            </div>

            <div className="order-progress">
                <h3>Прогресс доставки</h3>
                <div className="progress-steps">
                    {currentOrder.steps.map((step, idx) => (
                        <div
                            key={idx}
                            className={`step ${step.completed ? 'completed' : ''}`}
                        >
                            <div className="step-marker"></div>
                            <div className="step-info">
                                <div className="step-status">{step.status}</div>
                                {step.time && (
                                    <div className="step-time">
                                        {new Date(step.time).toLocaleString('ru-RU')}
                                    </div>
                                )}
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            <div className="order-items">
                <h3>Товары в заказе</h3>
                <table>
                    <thead>
                    <tr>
                        <th>Наименование</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th>Сумма</th>
                    </tr>
                    </thead>
                    <tbody>
                    {currentOrder.items.map(item => (
                        <tr key={item.id}>
                            <td>{item.name}</td>
                            <td>{item.quantity}</td>
                            <td>{item.price.toLocaleString('ru-RU')} ₽</td>
                            <td>{(item.price * item.quantity).toLocaleString('ru-RU')} ₽</td>
                        </tr>
                    ))}
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colSpan="3"><strong>Итого:</strong></td>
                        <td><strong>{currentOrder.totalPrice.toLocaleString('ru-RU')} ₽</strong></td>
                    </tr>
                    </tfoot>
                </table>
            </div>

            <div className="order-actions">
                <button onClick={() => fetchOrder(currentOrder.id)} className="refresh-btn">
                    🔄 Обновить
                </button>

                {currentOrder.status !== 'delivered' && (
                    <select
                        onChange={(e) => handleStatusChange(e.target.value)}
                        defaultValue=""
                    >
                        <option value="" disabled>Изменить статус</option>
                        {['created', 'processing', 'shipped', 'delivered']
                            .filter(s => s !== currentOrder.status)
                            .map(status => (
                                <option key={status} value={status}>{status}</option>
                            ))
                        }
                    </select>
                )}
            </div>
        </div>
    );
});
