// frontend/atomic/zustand/src/components/OrderSearch.jsx
import React, { useState } from 'react';
import { useOrderStore } from '../store/useOrderStore';
import { useOrderActions } from '../hooks/useOrderActions';

export const OrderSearch = () => {
    const [inputValue, setInputValue] = useState('');
    const [viewMode, setViewMode] = useOrderStore(state => [state.viewMode, state.setViewMode]);
    const loading = useOrderStore(state => state.loading);
    const { fetchOrder } = useOrderActions();

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (inputValue.trim()) {
            setViewMode('single');
            await fetchOrder(inputValue.trim());
        }
    };

    return (
        <div className="order-search">
            <form onSubmit={handleSubmit}>
                <input
                    type="text"
                    value={inputValue}
                    onChange={(e) => setInputValue(e.target.value)}
                    placeholder="Введите номер заказа (например: 12345)"
                    disabled={loading}
                />
                <button type="submit" disabled={loading}>
                    {loading ? 'Загрузка...' : 'Найти'}
                </button>
            </form>

            <div className="view-mode-buttons">
                <button
                    onClick={() => setViewMode('single')}
                    className={viewMode === 'single' ? 'active' : ''}
                >
                    Поиск заказа
                </button>
                <button
                    onClick={() => setViewMode('list')}
                    className={viewMode === 'list' ? 'active' : ''}
                >
                    Все заказы
                </button>
                <button
                    onClick={() => setViewMode('stats')}
                    className={viewMode === 'stats' ? 'active' : ''}
                >
                    Статистика
                </button>
            </div>
        </div>
    );
};

// frontend/atomic/elf/src/app/components/order-search.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { OrderFacade, OrderQuery } from '../state';

@Component({
  selector: 'app-order-search',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="order-search">
      <form (ngSubmit)="onSubmit()">
        <input type="text" [(ngModel)]="value" name="order" placeholder="Введите номер заказа (например: 12345)" [disabled]="(loading$ | async) ?? false" />
        <button type="submit" [disabled]="(loading$ | async) ?? false">Найти</button>
      </form>
      <div class="view-mode-buttons">
        <button (click)="facade.setViewMode('single')" [class.active]="(viewMode$ | async) === 'single'">Поиск заказа</button>
        <button (click)="facade.setViewMode('list')" [class.active]="(viewMode$ | async) === 'list'">Все заказы</button>
        <button (click)="facade.setViewMode('stats')" [class.active]="(viewMode$ | async) === 'stats'">Статистика</button>
      </div>
    </div>
  `,
  styles: [],
})
export class OrderSearchComponent {
  private query = inject(OrderQuery);
  value = '';
  loading$ = this.query.loading$;
  viewMode$ = this.query.viewMode$;

  constructor(public facade: OrderFacade) {}

  async onSubmit() {
    if (this.value.trim()) {
      await this.facade.fetchOrder(this.value.trim());
    }
  }
}
