// frontend/tabular/redux/src/App.jsx
// src/App.jsx
import React from 'react';
import { useOrdersState } from './hooks/useOrderSelectors';
import { useFavoriteOrders } from './hooks/useOrderSelectors';
import { OrderSearch } from './components/OrderSearch';
import { OrderDetails } from './components/OrderDetails';
import { OrderList } from './components/OrderList';
import { OrderStats } from './components/OrderStats';
import { Notification } from './components/Notification';

import './App.css';

function App() {
    const { viewMode, error } = useOrdersState();
    const favoriteOrders = useFavoriteOrders();

    return (
        <div className="app">
            <header className="app-header">
                <h1>📦 Отслеживание заказов (Redux)</h1>
                <div className="header-info">
                    <span>Избранных: {favoriteOrders.length}</span>
                </div>
            </header>

            <Notification />

            <main className="app-main">
                <OrderSearch />

                {error && (
                    <div className="error-message">
                        ⚠️ {error}
                    </div>
                )}

                <div className="content">
                    {viewMode === 'single' && <OrderDetails />}
                    {viewMode === 'list' && <OrderList />}
                    {viewMode === 'stats' && <OrderStats />}
                </div>

                {favoriteOrders.length > 0 && viewMode === 'single' && (
                    <div className="favorites-sidebar">
                        <h3>Избранные заказы</h3>
                        {favoriteOrders.map(order => (
                            <div key={order.id} className="favorite-item">
                                <span>#{order.id}</span>
                                <span className={`status status-${order.status}`}>
                  {order.status}
                </span>
                            </div>
                        ))}
                    </div>
                )}
            </main>
        </div>
    );
}

export default App;

// frontend/atomic/akita/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HttpClientModule } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { NotificationComponent, OrderSearchComponent, OrderDetailsComponent, OrderListComponent, OrderStatsComponent } from './components';
import { OrderQuery } from './state';
import { inject } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet,
    HttpClientModule,
    CommonModule,
    NotificationComponent,
    OrderSearchComponent,
    OrderDetailsComponent,
    OrderListComponent,
    OrderStatsComponent,
  ],
  template: `
    <div class="app">
      <header class="app-header">
        <h1>📦 Отслеживание заказов (Akita)</h1>
        <div class="header-info">
          <span>Избранных: {{ (favorites$ | async)?.length }}</span>
        </div>
      </header>

      <app-notification></app-notification>

      <main class="app-main">
        <app-order-search></app-order-search>

        <div *ngIf="error$ | async as error" class="error-message">⚠️ {{error}}</div>

        <div class="content">
          <app-order-details *ngIf="(viewMode$ | async) === 'single'"></app-order-details>
          <app-order-list *ngIf="(viewMode$ | async) === 'list'"></app-order-list>
          <app-order-stats *ngIf="(viewMode$ | async) === 'stats'"></app-order-stats>
        </div>
      </main>
    </div>
  `,
  styles: [],
})
export class AppComponent {
  private query = inject(OrderQuery);
  favorites$ = this.query.favorites$;
  viewMode$ = this.query.viewMode$;
  error$ = this.query.error$;
}
