// frontend/atomic/elf/src/app/components/order-list.component.ts
import { Component, OnInit, OnDestroy, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { OrderFacade, OrderQuery } from '../state';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-order-list',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="order-list">
      <div class="filters" *ngIf="filters$ | async as filters">
        <input type="text" placeholder="Поиск по ID, клиенту, трек-номеру" [value]="filters.search" (input)="updateFilters({search: $any($event.target).value})" />
        <select [value]="filters.status" (change)="updateFilters({status: $any($event.target).value})">
          <option value="">Все статусы</option>
          <option value="created">Created</option>
          <option value="processing">Processing</option>
          <option value="shipped">Shipped</option>
          <option value="delivered">Delivered</option>
        </select>
        <input type="text" placeholder="Город" [value]="filters.city" (input)="updateFilters({city: $any($event.target).value})" />
        <button (click)="facade.fetchOrders()" [disabled]="loading$ | async">{{ (loading$ | async) ? 'Загрузка...' : 'Обновить' }}</button>
      </div>

      <div class="orders-grid">
        <div *ngFor="let order of orders$ | async" class="order-card">
          <div class="order-card-header">
            <h3 (click)="open(order.id)">Заказ #{{order.id}}</h3>
            <button class="favorite-btn-small" (click)="toggleFavorite(order.id); $event.stopPropagation()">{{ facade.isFavorite(order.id) ? '★' : '☆' }}</button>
          </div>
          <p><strong>Клиент:</strong> {{order.customer}}</p>
          <p><strong>Город:</strong> {{order.city}}</p>
          <p><strong>Статус:</strong> <span class="status status-{{order.status}}">{{order.status}}</span></p>
          <p><strong>Сумма:</strong> {{order.totalPrice | number}} ₽</p>
          <p><strong>Дата:</strong> {{ order.createdAt | date:'dd.MM.yyyy' }}</p>
        </div>
      </div>

      <ng-container *ngIf="pagination$ | async as p">
        <div class="pagination" *ngIf="p.totalPages > 1">
          <button (click)="changePage(p.page - 1)" [disabled]="p.page === 1">← Назад</button>
          <span>Страница {{p.page}} из {{p.totalPages}}</span>
          <button (click)="changePage(p.page + 1)" [disabled]="p.page === p.totalPages">Вперед →</button>
        </div>
      </ng-container>
    </div>
  `,
  styles: [],
})
export class OrderListComponent implements OnInit, OnDestroy {
  private query = inject(OrderQuery);
  orders$ = this.query.selectAll();
  loading$ = this.query.loading$;
  filters$ = this.query.filters$;
  pagination$ = this.query.pagination$;
  private sub?: Subscription;

  constructor(public facade: OrderFacade) {}

  ngOnInit() {
    this.sub = this.filters$.subscribe(() => this.facade.fetchOrders());
  }

  ngOnDestroy() {
    this.sub?.unsubscribe();
  }

  open(id: string) {
    this.facade.fetchOrder(id);
    this.facade.setViewMode('single');
  }

  toggleFavorite(id: string) {
    this.facade.toggleFavorite(id);
  }

  updateFilters(filters: any) {
    this.facade.updateFilters(filters);
  }

  changePage(page: number) {
    this.facade.updateFilters({ page });
  }
}

// frontend/tabular/redux/src/components/OrderList.jsx
import React, { useEffect } from 'react';
import { useFilteredOrders, useOrdersState } from '../hooks/useOrderSelectors';
import { useOrderActions } from '../hooks/useOrderActions';

export const OrderList = () => {
    const filteredOrders = useFilteredOrders();
    const { filters, pagination, loading, favorites } = useOrdersState();
    const { fetchOrders, fetchOrder, toggleFavorite, updateFilters, setViewMode } = useOrderActions();

    useEffect(() => {
        fetchOrders();
    }, [filters]);

    const isFavorite = (id) => favorites.includes(id);

    const handleOrderClick = (orderId) => {
        fetchOrder(orderId);
        setViewMode('single');
    };

    const handlePageChange = (newPage) => {
        updateFilters({ page: newPage });
    };

    return (
        <div className="order-list">
            <div className="filters">
                <input
                    type="text"
                    placeholder="Поиск по ID, клиенту, трек-номеру"
                    value={filters.search}
                    onChange={(e) => updateFilters({ search: e.target.value })}
                />

                <select
                    value={filters.status}
                    onChange={(e) => updateFilters({ status: e.target.value })}
                >
                    <option value="">Все статусы</option>
                    <option value="created">Created</option>
                    <option value="processing">Processing</option>
                    <option value="shipped">Shipped</option>
                    <option value="delivered">Delivered</option>
                </select>

                <input
                    type="text"
                    placeholder="Город"
                    value={filters.city}
                    onChange={(e) => updateFilters({ city: e.target.value })}
                />

                <button onClick={fetchOrders} disabled={loading}>
                    {loading ? 'Загрузка...' : 'Обновить'}
                </button>
            </div>

            <div className="orders-grid">
                {filteredOrders.map(order => (
                    <div key={order.id} className="order-card">
                        <div className="order-card-header">
                            <h3 onClick={() => handleOrderClick(order.id)}>
                                Заказ #{order.id}
                            </h3>
                            <button
                                onClick={(e) => {
                                    e.stopPropagation();
                                    toggleFavorite(order.id);
                                }}
                                className="favorite-btn-small"
                            >
                                {isFavorite(order.id) ? '★' : '☆'}
                            </button>
                        </div>
                        <p><strong>Клиент:</strong> {order.customer}</p>
                        <p><strong>Город:</strong> {order.city}</p>
                        <p><strong>Статус:</strong>
                            <span className={`status status-${order.status}`}>
                                {order.status}
                            </span>
                        </p>
                        <p><strong>Сумма:</strong> {order.totalPrice.toLocaleString('ru-RU')} ₽</p>
                        <p><strong>Дата:</strong> {new Date(order.createdAt).toLocaleDateString('ru-RU')}</p>
                    </div>
                ))}
            </div>

            {pagination.totalPages > 1 && (
                <div className="pagination">
                    <button
                        onClick={() => handlePageChange(pagination.page - 1)}
                        disabled={pagination.page === 1}
                    >
                        ← Назад
                    </button>
                    <span>
                        Страница {pagination.page} из {pagination.totalPages}
                    </span>
                    <button
                        onClick={() => handlePageChange(pagination.page + 1)}
                        disabled={pagination.page === pagination.totalPages}
                    >
                        Вперед →
                    </button>
                </div>
            )}
        </div>
    );
};
